services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, GestoriaBundle\Entity\User, "AdminBundle:UserAdmin"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        public: true
    admin.roles:
        class: AdminBundle\Admin\RoleAdmin
        arguments: [~, GestoriaBundle\Entity\Role, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Roles }
        public: true
    admin.work:
        class: AdminBundle\Admin\WorkAdmin
        arguments: [~, GestoriaBundle\Entity\Work, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Obras }
        public: true
        
