admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

gestoria:
    resource: "@GestoriaBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

mvms_api:
    type:     rest
    prefix:   /api/v1
    resource: "@ApiBundle/Resources/config/routing.yml"    