# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        GestoriaBundle\Entity\User: {algorithm: sha512, iterations: 10}
    
    
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class : GestoriaBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
                
    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }       
        
    role_hierarchy: 
        ROLE_ADMIN: [ROLE_SONATA_ADMIN]
            