# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.helper_view:
        class: AppBundle\Twig\HelperView
        public: true
        tags: 
            - { name : twig.extension}
    app.filter_view:
        class: AppBundle\Twig\FilterView
        public: true
        tags: 
            - { name : twig.extension}
            
    
