sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]    
        # ...
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts: [user]
        sonata.block.service.notification:
        sonata.block.service.rss:
            
sonata_admin:   
#    security:
#        handler: sonata.admin.security.handler.role
    title:      ArquiGestor
    title_logo:           bundles/gestoria/img/gestoria.jpg
    templates:
        layout: AdminBundle::standard_layout.html.twig  
    dashboard:
        blocks:
#            -
#                position: left
#                type: sonata.admin.block.admin_list
#                settings:
#                    groups: [sonata_admin.group.backoffice]
            -   
                position: center
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2><code style="color:#428bca;padding-left: 289px;">Consultoría y Gestoría Urbana</code></h2>          
        groups:
            sonata_admin.group.backoffice:
                label: Backoffice
                label_catalogue: AppBundle
                items:
                    - admin.user
                    - admin.roles              
            sonata_admin.group.gestor:
                label: Gestoría
                label_catalogue: AppBundle
                items:
                    - admin.work
#                    - admin.roles              