login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }
    
login_check:
    path: /login_check

logout:
    path: /logout
    
blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
    
blog_add_tag:
    path:  /tag/add
    defaults: { _controller: BlogBundle:Tag:addTag }
