AppBundle\Entity\Curso:
    properties:
        titulo:
            - NotBlank: { message: "El título no puede estar en vacío"}
            - Length:
                min: 2
                minMessage: "El Título debe tener mas de dos caracteres"
        description: 
            - NotBlank: { message: "La descripción no puede estar en vacía"}
        precio: 
            - Type:
                type: numeric
                message: "El precio tiene que ser numérico"